### ISSUE TITLE
`extra_platforms` issue: Multiple platforms match current OS for a debian docker image

### ISSUE THREAD

**Issue by mrevoir** [kdeldycke/click-extra#1083]
https://github.com/kdeldycke/extra-platforms/issues/72

**Comment by kdeldycke** [comment]
Good catch! Will fix that as soon as I finish releasing a new `extra_platforms` package.

**Comment by kdeldycke** [comment]
`extra-platforms` 1.3.1, which fix the issue, is now available on PyPi: https://pypi.org/project/extra-platforms
