### ISSUE TITLE
`ValueError: Can't guess the target configuration data type` when `count=True`

### ISSUE THREAD

**Issue by rasa** [kdeldycke/click-extra#170]
In click_extra/config.py", line 235, in map_option_type, I got the error
```pytb
ValueError: Can't guess the target configuration data type of <Option verbose> prameter.
```

With this option
```python
@click.option('-v', '--verbose', count=True)
```

If I change it to
```python
@click.option('-v', '--verbose', count=True, type=int)
```

it works.

**Comment by kdeldycke** [comment]
Oh I see. You have defined your own `--verbose` option that is a count type so you'll have the possibility pass the classical `-vvv` pattern to increase verbosity. Is that right?

In which case yes, this seems to be an unsupported edge-case for the moment and the `type=int` parameter is a smart workaround. I guess I can add support for that use-case and have `count=True` imply `type=int`.

**Comment by rasa** [comment]
You nailed it. While I migrated to using `verbosity_option()`, as it's cleaner, it's still helpful to have it work with `count`. Thanks for the quick response, and the awesome package.

**Comment by kdeldycke** [comment]
The fix has been pushed upstream. I'll cut a release soon once I fixed all the test suite.
