### ISSUE TITLE
Passing `logging.root` to `verbosity_option()` doesn't set logging level

### ISSUE THREAD

**Issue by rasa** [kdeldycke/click-extra#174]
Using click-extra, 3.0.1, and running this script:
```python
import logging

import click_extra as click

@click.command()
@click.logging.verbosity_option(default_logger=logging.getLogger())
def cli():
    logging.warning("logging at warning level")
    logging.info("logging at info level")
    logging.debug("logging at debug level")
    logging.getLogger().setLevel(click.logging.logger.level)
    logging.warning("logging at warning level")
    logging.info("logging at info level")
    logging.debug("logging at debug level")

if __name__ == "__main__":
    cli()
```
via:
```sh
python issue174.py -v DEBUG
```
it produces:
```console
Traceback (most recent call last):
  File "c:\github\rasa\click-extra-tests\issue174.py", line 7, in <module>
    def cli():
  File "C:\Python310\lib\site-packages\cloup\_params.py", line 52, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
TypeError: VerbosityOption.__init__() got multiple values for argument 'default_logger'
```
Passing `default_logger=None` or removing the parameter fixes the issue.

**Comment by rasa** [comment]
With version 3.2.5, I now use:
```python
@click_extra.extra_command(
    params=[
        click_extra.VerbosityOption(logging.getLogger(), default="DEBUG"),
    ]
)  # type: ignore
```
so this issue can be closed.

**Comment by kdeldycke** [comment]
Thanks @rasa for the report and follow up! I just added your example to the documentation at: https://kdeldycke.github.io/click-extra/logging.html

Do you think we should adjust the defaults of `click_extra.VerbosityOption` to make it easier to use?

**Comment by rasa** [comment]
> Do you think we should adjust the defaults of `click_extra.VerbosityOption` to make it easier to use?

@kdeldycke I think it's fine, as long as it's documented. And it is in this case.

**Comment by kdeldycke** [comment]
Thanks @rasa for the feedback. In the future, feel free to suggest anything that can make click-extra easier to use!
