### ISSUE TITLE
`extra_command` not found?

### ISSUE THREAD

**Issue by rasa** [kdeldycke/click-extra#218]
I'm sure I'm doing something wrong, but using 3.01:
```python
from click_extra import extra_command
...
@extra_command(
```
produces:
```pytb
ImportError: cannot import name 'extra_command' from 'click_extra'
```
and
```python
import click_extra
...
@click_extra.extra_command(
```
produces:
```pytb
AttributeError: module 'click_extra' has no attribute 'extra_command'
```

**Comment by kdeldycke** [comment]
Hmmm. That's really strange. As you can see in v3.0.1 the `extra_command` and `extra_group` decorators are available at the root of the package: https://github.com/kdeldycke/click-extra/blob/10a58b394fcc7494ecbae2fff07cc28e6bf261f9/click_extra/__init__.py#L68-L69

Can you double-check the `click_extra` you are using is v3.0.1? What's the result of `print(click_extra.__version__)`?

**Comment by rasa** [comment]
System config issue. My bad. Sorry for the noise.

**Comment by kdeldycke** [comment]
No worries @rasa, and thanks for double checking. Do not hesitate next time to open an issue if you have any doubt.
