### ISSUE TITLE
Question: Get loaded config file path

### ISSUE THREAD

**Issue by puzzlepeaches** [kdeldycke/click-extra#319]
Hey there!

Awesome project, quick question. Is there a way for me to retrieve the resolved path to the config file specified on the command line? 

I would like to load the config file in other portions of my application without having to specify all options first with click. I would like to do something like:

```python
@config_option()
def main():
    config_path = config['path']
    do_something(config_path)
```

While this may seem a bit convoluted, it would be useful in my situation as I am loading the config to pull variables for FastAPI routes that don't need to be initialized immediately on runtime. Currently, I am having to hardcode the path to my config in the classes supporting other API routes in separate files throughout the app:

```python
pwd = os.path.dirname(os.path.realpath(__file__))
with open(f"{pwd}/../../config.yaml", "r") as f:
     config = yaml.safe_load(f)
```

You can see the problem users will experience here if this application is deployed on a different host.

I combed through the documentation, but I'm not seeing anything that would enable me to do this. Any thoughts you have would be greatly appreciated. Thanks!

**Comment by kdeldycke** [comment]
That's a reasonable thing to have around. I can see the value of reusing the path of the config file. Let me check the sources...

**Comment by kdeldycke** [comment]
Here it is: https://kdeldycke.github.io/click-extra/commands.html#introspecting-parameters
