### ISSUE TITLE
Coloring help for sub commands

### ISSUE THREAD

**Issue by omidmeh** [kdeldycke/click-extra#479]
## Credit where it's due!
First off, hats off to you @kdeldycke for putting the time to implement this. I've just found this and it's saved me so much time in creating a readable help page for the cli that I'm making! 

## Issue
I'm seeing the behavior where the help for the subcommands isn't colored, even though the help for the main command (group) is properly colored. 

Is there a way to make the coloring apply to subcommands as well?

## How to recreate
This is s simple code to recreate it (small modification from the docs):
```py
@extra_group()
@option("--dummy-flag/--no-flag")
@option("--my-list", multiple=True)
@pass_context
def my_cli(ctx, dummy_flag, my_list):
    echo(f"dummy_flag    is {dummy_flag!r}")
    echo(f"my_list       is {my_list!r}")
    echo(f"Raw parameters:            {ctx.meta.get('click_extra.raw_args', [])}")
    echo(f"Loaded, default values:    {ctx.default_map}")
    echo(f"Values passed to function: {ctx.params}")

@my_cli.command()
@pass_context
@option("--int-param", type=int, default=10)
def subcommand(ctx, int_param):
    echo(f"int_parameter is {int_param!r}")
    echo(ctx.meta.get('click_extra.raw_args', []))
    
if __name__ == '__main__':
    my_cli()
```

Where `--help` is colored, but `subcommand --help` is not`
![image](https://user-images.githubusercontent.com/5945494/227647191-fe656208-b6dd-44b0-9a82-47fd86d22529.png)

## What I've tried
1. I tried setting the formatter settings for the command to the default from click_extra, but that had no effect:
```py
@my_cli.command(
    formatter_settings=click_extra.colorize.HelpExtraFormatter.settings()
)
```
2. Then I tried manually setting the theme to the `dark()` theme from cloup which did work, but it's not the click-extra theme that I've started to love!
```py
@my_cli.command(
    formatter_settings=click_extra.colorize.HelpExtraFormatter.settings(
       theme=cloup.HelpTheme.dark()
       )
    )
```
outputs:
![image](https://user-images.githubusercontent.com/5945494/227646947-01892686-fa93-4363-869f-663ba34f8afb.png)
3. Finally, I also managed to set the colors of the theme manually, but it's not as comprehensive as the default theme of click-extra!
```py
@my_cli.command(
    formatter_settings=click_extra.colorize.HelpExtraFormatter.settings(
       theme=click_extra.colorize.HelpExtraTheme(
                invoked_command=cloup.Style(fg='bright_yellow'),
                heading=cloup.Style(fg='bright_white', bold=True),
                constraint=cloup.Style(fg='magenta'),
                col1=cloup.Style(fg='bright_yellow'),
            )
       )
    )
```

**Comment by MePsyDuck** [comment]
I had partial success using `@extra_command()` decorator on my subcommands instead of `@my_cli.command` and adding the subcommands to group via `add_command`. The output was colored, but help text was bugged as described in #489.

**Comment by kdeldycke** [comment]
Thanks @omidmeh for the kind words and the detailed bug report. I can confirm it and I'll try to fix this issue in the next few days.

**Comment by kdeldycke** [comment]
Oh and thanks @MePsyDuck for the additional feedback. I now understand the sequence of events that led you to report #489. Looks like the 2 issues are somewhat linked. And now that I fixed #489, I might add some syntactic sugar to reduce the surprises on both issues.

**Comment by kdeldycke** [comment]
The Tl;Dr of the fix is that `@my_cli.command()` is now returning an instance of `@click_extra.extra_command()` behind the scene, but without the default collection of extra options.

**Comment by kdeldycke** [comment]
FYI click-extra v3.10.0 has just been released.
