### ISSUE TITLE
Removing all default extra options from `@extra_command` disable help screen colouring

### ISSUE THREAD

**Issue by isezen** [kdeldycke/click-extra#534]
Hello, I searched but couldn't figured out. Is there a way remove extra options from `extra_command`? I just want to use colorization feature of the package but do not want to add extra options to the app. Thanks.

**Comment by kdeldycke** [comment]
You can change the default parameters from `@extra_command` with the `params=` argument. This is referenced in the documentation at: https://kdeldycke.github.io/click-extra/commands.html#change-default-options

So this should work for you:
```python
from click_extra import extra_command

@extra_command(params=[])
def cli():
   pass
```

Now considering your question, maybe I should add an explicit explanation in the docs for that particular case of stripping *all* default options.

**Comment by isezen** [comment]
Thank you very much. I read all the docs but there was not a clear explanation. I had found a way but your solution is more clear and easy.

**Comment by isezen** [comment]
I just tried your solution but it does not `colorize` the help output. :(

I created `my_click_extra.py` file with following content and If I use following `group` decorator by importing, then it works.

```python
import cloup as _cloup
import click_extra as _ce

def _extra_params():
    return [
        _ce.colorize.HelpOption(),
    ]

group = _ce.decorators.decorator_factory(
    dec=_cloup.group,
    cls=_ce.commands.ExtraGroup,
    params=_extra_params,
)
```

**Comment by kdeldycke** [comment]
Thanks @isezen for the code example.

So yes you are right, the solution I proposed earlier could not work. I just realized that most of the color-related behavior are implemented in Click Extra's `--help` and `--no-color` custom options.

I need to think about how to make your use-case easy. Something like creating another set of decorators, like `@colored_command()` and `@colored_group()`, which would be like `@extra_command` and `@extra_group`, but with the minimal options to make the output coloured.

I'll put that in the backburner as I have other things to stabilize in Click Extra before I can cut a release. But if you feel like creating a PR for that, I'll be happy to merge it upstream! :)

**Comment by isezen** [comment]
Thank you for encouraging me to be included in the project :) You are very kind. I created a PR for your approval. I'm studying `click_extra`, `cloup` and `click` code, I hope I can contribute more in the future. Thank you very much for your work.

**Comment by kdeldycke** [comment]
For the record, new colour-preserving decorators were proposed at: https://github.com/kdeldycke/click-extra/pull/543
