### ISSUE TITLE
Set custom logger or overwrite verbosity option

### ISSUE THREAD

**Issue by MLNW** [kdeldycke/click-extra#67]
Hey, I'm trying out your library mainly to add some colors to the help page and use the configuration file mechanism.

Before I used [rich](https://github.com/Textualize/rich) for logging and general printing purposes.
Now with your library the logging configuration used is overwritten.

I was looking for a way to restore the old behavior but I didn't find a way to provide my own logging configuration.

Is there a way that I missed or if there is not could we add it?

**Comment by kdeldycke** [comment]
Thanks @MLNW for considering my little project! 😃

`click-extra` is currently in an acceptable MVP state and good enough for me that I can share it between my 2 main projects ([`meta-package-manager`] and [`mail-deduplicate`]). Which means there's actually some hard-coded stuff, low documentation and lots of coupling that can be annoying. And I guess you stumble upon that.

I was hoping to iron things out depending on external interest. You're my first user, so yeah, sorry for the trouble! 😅

Do you have an example on how you are actually using the help screen colouring and configuration file loading? Does that work? I can reuse your examples as a base to improve the documentation. I only took the time to properly document the `--config` parameter.

Now I was planning at one point to use `rich` myself for logging. Can you show me how you'd like to use `click-extra` with `rich`?

**Comment by kdeldycke** [comment]
Defaults logger are now better supported and documented at: https://kdeldycke.github.io/click-extra/logging.html

(See #174 for more discussion on the topic).
