### ISSUE TITLE
Expose configuration file path in context

### ISSUE THREAD

**Issue by jasondamour** [kdeldycke/click-extra#673]
Hi!

I'm not sure I understand why [this issue](https://github.com/kdeldycke/click-extra/issues/319) was closed. The OP asked for a way to programmatically get the path to the resolved config files, and the provided solution only lets you access explicitly passed args. I'm actually looking for a way to get implicitly determined config file path. This seems very useful to me, my program needs to write back to config files. 

For example, if I call `my_cli command` and it reads a value from `~/.my_cli/config.yaml`, how do I fetch the path `~/.my_cli/config.yaml` without re-implementing click_extra's load function?

Thanks, and sorry if it was already answered.

**Comment by kdeldycke** [comment]
Oh no I get it now. You are right to point ou the issue. Re-reading the whole stuff I just realize there was a blind spot.

In #319 the user was looking for the content of the config file to be reused elsewhere in its CLI. You can do so with `default_map` from the context: https://kdeldycke.github.io/click-extra/config.html#get-configuration-values

But my fix was not complete, as you can't get the *path* of the configuration file anywhere, even in `default_map`.

Thanks for pointing it out! I think I can fix this reasonably fast. The hardest work will be updating the docs! 😅

**Comment by jasondamour** [comment]
Thank you! Great project. LMK if you need a contrib.

**Comment by kdeldycke** [comment]
I just pushed the implementation to the development branch. Here is the documentation to explain how to retrieve both the configuration file path and its parsed (and unfiltered) content: https://kdeldycke.github.io/click-extra/config.html#get-configuration-values

This feature will be part of the upcoming v4.6.0 release of Click Extra.
