### ISSUE TITLE
Unrecognized `<Option warn_error_options>` parameter from `dbt` subcommand

### ISSUE THREAD

**Issue by jasondamour** [kdeldycke/click-extra#721]
Hello,

I'm trying to create a wrapper for an open-source project using click. Here is the `dbt` [click command](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/cli/main.py#L122). I am then trying to add the `dbt` command as a subcommand to my CLI, like so:
```python
from dbt.cli.main import cli

@click_extra.extra_group(params=[])
@click_extra.pass_context
def main(ctx,):
    # my root CLI group
    pass

# Here I would like to add the entirety of the `dbt` command as a sub-functionality of my CLI
main.add_command(cmd=cli, name='dbt')
```

This code results in:
```shell-session
$ mycli dbt --help
...
...
...
```
```pytb
  File "/opt/homebrew/lib/python3.11/site-packages/click_extra/config.py", line 428, in load_conf
    conf = self.merge_conf(user_conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click_extra/config.py", line 368, in merge_conf
    valid_conf = self.recursive_update(self.params_template, user_conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click_extra/parameters.py", line 479, in params_template
    self.build_param_trees()
  File "/opt/homebrew/lib/python3.11/site-packages/click_extra/parameters.py", line 465, in build_param_trees
    merge(types, self.init_tree_dict(*keys, leaf=self.get_param_type(param)))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click_extra/parameters.py", line 430, in get_param_type
    raise ValueError(msg)
ValueError: Can't guess the appropriate Python type of <Option warn_error_options> parameter.
```

I'm not sure if this is an issue with click_extra, or (more likely) my implementation, or (also possible) the dbt implementation of click is simply not compatible with click_extra. Any insight would be helpful, but I understand if the issue is outside of click_extra that not much could be done. Thanks

**Comment by kdeldycke** [comment]
Now that's a use-case I was not expecting. I never thought to use Click Extra as a wrapper to enhance another vanilla Click CLI. But I like the idea and the tentative! 🤠 Sounds hackish enough to trigger my curiosity! 😁

Ok so the problem seems to be that Click Extra has issues recognizing the custom nature of `dbt`'s `<Option warn_error_options> parameter`. Which seems to be defined at:

https://github.com/dbt-labs/dbt-core/blob/7eedfcd2742fcf789200a4b829c8c2eb98369089/core/dbt/cli/params.py#L586-L593

Let's dig deeper...

**Comment by kdeldycke** [comment]
That was a big surprise, but your instinct was good. I just pushed a small fix (see 758a06373d28d837bfcc4bf10dcac19d22e1e24f), and... it works! 🎉

Here are the details of my experiments:

```shell-session
$ poetry run python -m pip install dbt-core
(...)

$ poetry run dbt --version
Core:
  - installed: 1.6.1
  - latest:    1.6.1 - Up to date!

Plugins:

```

```shell-session
$ cat ./dbt_wrap.py
```

```python
from click_extra import extra_group
from dbt.cli.main import cli as dbt_cli


@extra_group
def main():
    pass


main.add_command(cmd=dbt_cli, name='dbt')


if __name__ == '__main__':
    main()
```

```shell-session
$ poetry run python ./dbt_wrap.py --help
Usage: dbt_wrap.py [OPTIONS] COMMAND [ARGS]...

Options:
  --time / --no-time        Measure and print elapsed execution time.  [default:
                            no-time]
  --color, --ansi / --no-color, --no-ansi
                            Strip out all colors and all ANSI codes from output.
                            [default: color]
  -C, --config CONFIG_PATH  Location of the configuration file. Supports glob
                            pattern of local path and remote URL.  [default:
                            ~/Library/Application
                            Support/dbt_wrap.py/*.{toml,yaml,yml,json,ini,xml}]
  --show-params             Show all CLI parameters, their provenance, defaults
                            and value, then exit.
  -v, --verbosity LEVEL     Either CRITICAL, ERROR, WARNING, INFO, DEBUG.
                            [default: WARNING]
  --version                 Show the version and exit.
  -h, --help                Show this message and exit.

Commands:
  dbt  An ELT tool for managing your SQL transformations and data models.
```

**Comment by kdeldycke** [comment]
But the real power of Click Extra is its ability to introspect the whole parameter tree of `dbt`:
```shell-session
$ poetry run python ./dbt_wrap.py --show-params
```
<img width="2499" alt="Screenshot 2023-09-05 at 10 43 00" src="https://github.com/kdeldycke/click-extra/assets/159718/dbc6e678-ef42-40b7-8808-12961c32ce59">

Which also means you can feed that CLI with a custom configuration via `--config`... Which opens a lot of possibility for legacy Click-based CLI.

**Comment by jasondamour** [comment]
Awesome! Thanks for following up on this. I already implemented a workaround just using the [dbt invoker](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/cli/main.py#L74), but i will revisit the click approach soon!

**Comment by kdeldycke** [comment]
For the record, I documented your particular use-case in the documentation: https://kdeldycke.github.io/click-extra/commands.html#third-party-commands-composition
