### ISSUE TITLE
`--show-params` skips nested subcommands

### ISSUE THREAD

**Issue by themoep** [kdeldycke/click-extra#725]
When using nested subcommands, `--show-params` skips anything deeper than subcommands.

As an example:
```python
#!/usr/bin/env python3

import click_extra

@click_extra.extra_group(params=[click_extra.ShowParamsOption()])
@click_extra.option("--first")
def main(first):
    print(first)

@main.group(params=[])
@click_extra.option("--second")
def subcommand(second):
    print(second)

@subcommand.command(params=[])
@click_extra.option("--third")
def subsubcommand(third):
    print(third)

if __name__ == "__main__":
    main()
```

Option `third` is not shown in the param output table. As far as I can tell this is due to `walk_params` not recursing into subcommands at https://github.com/kdeldycke/click-extra/blob/main/click_extra/parameters.py#L356

**Comment by kdeldycke** [comment]
This has been fixed by #726.
