### ISSUE TITLE
yaml config not working

### ISSUE THREAD

**Issue by gpongelli** [kdeldycke/click-extra#885]
Hi,
I've noticed that yaml config file isn't parsed, meanwhile json and toml are.

config.json:
```json
{
  "main": {
    "str_p": "ok"
  }
}
```

config.yaml:
```yaml
main:
  str_p: "ko"
```

config.toml:
```toml
[main]
str_p="toml"
```

code snippet
```python
MAIN_CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'], show_default=True)

@group(invoke_without_command=True, align_option_groups=False, 
       no_args_is_help=False,
       context_settings=MAIN_CONTEXT_SETTINGS) 
@config_option(default=str(Path.cwd() / "*.yaml"), formats=Formats.YAML)  # changed both to json to see differences
@verbosity_option(default="INFO")
@option("--str-p", type=str, default="oooo")
@pass_context
def main(ctx,str_p):
    echo(str_p)
```

both config.yaml and config.json are into the same folder and are loaded, but the output is different:
- json prints "ok" loaded from file
- toml prints "toml" loaded from file
- yaml prints "oooo" coming from **default value**

Am I doing something in a wrong way ?

useful versions:
python 3.11
click 8.1.7
click-extra 4.7.4

Thanks.

**Comment by gpongelli** [comment]
I found the solution: I've other yaml file in the repository, so when using *.yaml click-extra loads a file that it's not the "config" expected one.
I've found which file is loaded using `echo(f"Configuration location: {ctx.meta['click_extra.conf_source']}")` from docs.

Forcing to load "config.yaml" file in `@config_option(default=str(Path.cwd() / "config.yaml"), formats=Formats.YAML)` solves the issue.

**Comment by kdeldycke** [comment]
Thanks @gpongelli for giving Click Extra a try! Happy to see that you ended up finding the root cause of your issue!

And yes, the configuration loader is quite flexible so it's easy to make it work unexpectedly. You did the right thing looking into the `ctx.meta`. I'm glad I added these direct metadata there.
